# Generated by Django 3.2.5 on 2021-07-26 08:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=255, unique=True)),
                ('story_text', ckeditor.fields.RichTextField()),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='communities-stories-images')),
                ('admin_published', models.BooleanField(default=False)),
                ('admin_notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('meta_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('meta_lastupdated_datetime', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-meta_created_datetime', 'story_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('response_image', models.ImageField(blank=True, null=True, upload_to='communities-responses-images')),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('admin_approved', models.BooleanField(default=False)),
                ('admin_notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('meta_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('meta_lastupdated_datetime', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='communities.story')),
            ],
            options={
                'ordering': ['-meta_created_datetime'],
            },
        ),
    ]
