# Generated by Django 3.2.5 on 2021-08-05 13:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events-images')),
                ('location', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField(verbose_name='Event start date/time')),
                ('finish_datetime', models.DateTimeField(verbose_name='Event finish date/time')),
                ('booking_email', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_url', models.TextField(blank=True, null=True)),
                ('admin_published', models.BooleanField(default=False)),
                ('admin_notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('meta_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('meta_lastupdated_datetime', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'ordering': ['-start_datetime', '-finish_datetime', 'name', 'id'],
            },
        ),
    ]
