# Generated by Django 3.2.7 on 2021-10-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='Found in video URL after v= e.g. 1cK5uZ58XF0', max_length=50, null=True),
        ),
    ]
