# Generated by Django 3.2.8 on 2021-10-18 11:03

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
